app.authentik.host=http://localhost:9000
spring.http.clients.imperative.factory=simple

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.web.client=DEBUG

logging.level.nl.lekkeratlas=DEBUG