spring.application.name=lekkeratlas-worker

# The worker should not start an embedded web server.
spring.main.web-application-type=none

# Worker concurrency.
# Start conservative. can increase this later.
spring.rabbitmq.listener.simple.concurrency=1
spring.rabbitmq.listener.simple.max-concurrency=4
spring.rabbitmq.listener.simple.prefetch=1