spring.application.name=lekkeratlas-backend
# Authentik host can differ per environment, e.g.:
# local:  AUTHENTIK_HOST=http://localhost:9000
# prod:   AUTHENTIK_HOST=https://auth.example.com
app.authentik.host=${AUTHENTIK_HOST}

# Replace `your-provider-slug` with the slug of your Authentik OAuth2/OpenID provider/application.
app.authentik.issuer-uri=${app.authentik.host}/application/o/lekker-atlas/

spring.security.oauth2.client.registration.authentik.client-id=${AUTHENTIK_CLIENT_ID}
spring.security.oauth2.client.registration.authentik.client-secret=${AUTHENTIK_CLIENT_SECRET}

spring.security.oauth2.client.registration.authentik.scope=openid,profile,email
spring.security.oauth2.client.registration.authentik.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.authentik.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.authentik.client-authentication-method=client_secret_post

spring.security.oauth2.client.provider.authentik.issuer-uri=${app.authentik.issuer-uri}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${app.authentik.issuer-uri}


# Will replace later
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
