spring.application.name=lekkeratlas

# RabbitMQ Config
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}


# Good default for mixed long/short jobs in one queue.
spring.rabbitmq.listener.simple.prefetch=1

# TODO Keep SQL/web defaults out of this base file where possible.